version: "3.7"
services:
  example:
    build: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined    
    volumes:
    - "~/.ssh/id_rsa.pub:/home/user/.ssh/authorized_keys:ro"
    - "~/.gitconfig:/home/user/.gitconfig:ro"
    - "..:/go/src/github.com/maxbet1507/golang_sshd:rw"
    ports:
    - "10022:22"
  